contributing and delivery
NorthPage/telegraf-cookbook pull request #53
Opened 2017-10-14 13:30 UTC by Plork

https://github.com/NorthPage/telegraf-cookbook/issues/51

Don't want to intrude but since I was working on it anyway. Here is a draft from the chef-cookbooks community.

2017-10-16 10:37 UTC, fishnix requested changes

2017-10-16 10:37 UTC, fishnix commented on CONTRIBUTING.md
> +# Contributing to Chef Managed Community Cookbooks
`# Contributing to the telegraf Community Cookbook`

2017-10-16 10:37 UTC, fishnix commented on CONTRIBUTING.md
> +Not every contribution comes in the form of code. Submitting, confirming, and triaging issues is an important task for any project. At Chef we use GitHub to track all project issues.
~~At Chef we use GitHub to track all project issues.~~

2017-10-16 10:37 UTC, fishnix commented on CONTRIBUTING.md
> +All of our cookbooks can be found in our [GitHub organization](https://github.com/chef-client/). All cookbooks include GitHub issue templates to help gather information needed for a thorough review.
✂️

2017-10-16 10:37 UTC, fishnix commented on CONTRIBUTING.md
> +We ask you not to submit security concerns via GitHub. For details on submitting potential security issues please see <https://www.chef.io/security/>
~~For details on submitting potential security issues please see <https://www.chef.io/security/>~~

2017-10-16 10:37 UTC, fishnix commented on TESTING.md
> +This document describes the process for testing Chef community cookbooks using ChefDK.
`telegraf community cookbooks using ChefDK`

2017-10-16 10:37 UTC, fishnix commented on TESTING.md
> +A working ChefDK installation set as your system's default ruby. ChefDK can be downloaded at <https://downloads.chef.io/chef-dk/>
`A working ChefDK installation, preferably set as your system's default ruby. ChefDK can be downloaded at <https://downloads.chef.io/chef-dk/>`

2017-10-16 10:37 UTC, fishnix commented on .delivery/project.toml
> +remote_file = "https://raw.githubusercontent.com/chef-cookbooks/community_cookbook_tools/master/delivery/project.toml"
We aren't using delivery, I'd be ok with starting, but this needs to be added to our repo since this isn't a chef managed cookbook.

2017-10-16 10:37 UTC, fishnix commented on TESTING.md
> +## Local Delivery
This section should be updated since we aren't using Chef delivery.  I'm ok with keeping it though if you bring the project delivery file into the repo.

2017-10-16 11:59 UTC, Plork commented on TESTING.md
> +## Local Delivery
Only reason I use a delivery file is that I tend to do cookstyle/foodcritic and rspec locally before pushing to git.

This way you can do 'delivery local verify' and all those steps are then done. You can always run them manually 1 by 1 if preferred.

2017-10-16 12:02 UTC, Plork commented on .delivery/project.toml
> +remote_file = "https://raw.githubusercontent.com/chef-cookbooks/community_cookbook_tools/master/delivery/project.toml"
You want to add the file itself? A lot of cookbooks are pointing to the "community standards"  with the toml file. I could if it's an issue.

2017-10-27 15:33 UTC, fishnix requested changes
Sorry, found two more issues, otherwise looks good.

2017-10-27 15:33 UTC, fishnix commented on CONTRIBUTING.md
> +2. Create a GitHub Pull Request for your change, following the instructions in the pull request template.
~~, following the instructions in the pull request template~~

2017-10-27 15:33 UTC, fishnix commented on CONTRIBUTING.md
> +Sander van Zoest will update the CHANGELOG.md when releasing a new version of
`s/Sander van Zoest/The cookbook maintainers/`

2018-03-13 19:55 UTC, Plork commented
sorry it took a while ;)

2018-03-13 20:00 UTC, fishnix commented
Thanks for this!

2018-03-13 20:02 UTC, merged